/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoAn;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author rangc
 */
public class Main_F extends javax.swing.JFrame {

    /**
     * Creates new form Main_F
     */
    final String CoorRegex = "([-]+\\d+)|(\\d+)";
    final String lengthRegex = "\\d+";

    public Main_F() {
        initComponents();
        //p_heToaDo.setVisible(false);
        p_inputHinhCau.setVisible(false);
        p_inputHinhNon.setVisible(false);
        p_inputHHCN.setVisible(false);
        p_thongTinNon.setVisible(false);
        p_thongTinHHCN.setVisible(false);
        p_thongTinOto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_2D = new javax.swing.JButton();
        btnOto = new javax.swing.JButton();
        btnCoiXay = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnHinhCau = new javax.swing.JButton();
        btnHinhNon = new javax.swing.JButton();
        p_inputHinhNon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_xTamNon = new javax.swing.JTextField();
        tf_zTamNon = new javax.swing.JTextField();
        tf_yTamNon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_rNon = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tf_hNon = new javax.swing.JTextField();
        p_inputHinhCau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_xCau = new javax.swing.JTextField();
        tf_zCau = new javax.swing.JTextField();
        tf_yCau = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_rCau = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        p_thongTinNon = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lb_nonTam = new javax.swing.JLabel();
        lb_nonDinh = new javax.swing.JLabel();
        lb_nonA = new javax.swing.JLabel();
        lb_nonB = new javax.swing.JLabel();
        btn_HHCN = new javax.swing.JButton();
        p_inputHHCN = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_HCNX = new javax.swing.JTextField();
        tf_HCNY = new javax.swing.JTextField();
        tf_HCNZ = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_HCNR = new javax.swing.JTextField();
        tf_HCND = new javax.swing.JTextField();
        tf_HCNC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        p_heToaDo = new javax.swing.JPanel();
        p_thongTinToaDo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        p_thongTinOto = new javax.swing.JPanel();
        lb_oto1 = new javax.swing.JLabel();
        lb_oto2 = new javax.swing.JLabel();
        lb_oto4 = new javax.swing.JLabel();
        lb_oto3 = new javax.swing.JLabel();
        lb_oto6 = new javax.swing.JLabel();
        lb_oto5 = new javax.swing.JLabel();
        lb_oto8 = new javax.swing.JLabel();
        lb_oto7 = new javax.swing.JLabel();
        lb_oto10 = new javax.swing.JLabel();
        lb_oto9 = new javax.swing.JLabel();
        lb_oto12 = new javax.swing.JLabel();
        lb_oto11 = new javax.swing.JLabel();
        lb_oto14 = new javax.swing.JLabel();
        lb_oto13 = new javax.swing.JLabel();
        lb_oto16 = new javax.swing.JLabel();
        lb_oto15 = new javax.swing.JLabel();
        lb_oto18 = new javax.swing.JLabel();
        lb_oto17 = new javax.swing.JLabel();
        lb_oto20 = new javax.swing.JLabel();
        lb_oto19 = new javax.swing.JLabel();
        lb_oto22 = new javax.swing.JLabel();
        lb_oto21 = new javax.swing.JLabel();
        lb_oto24 = new javax.swing.JLabel();
        lb_oto23 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lb_2oto24 = new javax.swing.JLabel();
        lb_2oto23 = new javax.swing.JLabel();
        lb_2oto18 = new javax.swing.JLabel();
        lb_2oto17 = new javax.swing.JLabel();
        lb_2oto20 = new javax.swing.JLabel();
        lb_2oto19 = new javax.swing.JLabel();
        lb_2oto22 = new javax.swing.JLabel();
        lb_2oto21 = new javax.swing.JLabel();
        lb_2oto1 = new javax.swing.JLabel();
        lb_2oto2 = new javax.swing.JLabel();
        lb_2oto4 = new javax.swing.JLabel();
        lb_2oto3 = new javax.swing.JLabel();
        lb_2oto6 = new javax.swing.JLabel();
        lb_2oto5 = new javax.swing.JLabel();
        lb_2oto8 = new javax.swing.JLabel();
        lb_2oto7 = new javax.swing.JLabel();
        lb_2oto10 = new javax.swing.JLabel();
        lb_2oto9 = new javax.swing.JLabel();
        lb_2oto12 = new javax.swing.JLabel();
        lb_2oto11 = new javax.swing.JLabel();
        lb_2oto14 = new javax.swing.JLabel();
        lb_2oto13 = new javax.swing.JLabel();
        lb_2oto16 = new javax.swing.JLabel();
        lb_2oto15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        p_thongTinHHCN = new javax.swing.JPanel();
        lb_HHCN4 = new javax.swing.JLabel();
        lb_HHCN3 = new javax.swing.JLabel();
        lb_HHCN1 = new javax.swing.JLabel();
        lb_HHCN2 = new javax.swing.JLabel();
        lb_HHCN5 = new javax.swing.JLabel();
        lb_HHCN6 = new javax.swing.JLabel();
        lb_HHCN7 = new javax.swing.JLabel();
        lb_HHCN8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 690));

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_2D.setBackground(new java.awt.Color(255, 255, 255));
        btn_2D.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_2D.setText("2D");
        btn_2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2DActionPerformed(evt);
            }
        });
        jPanel1.add(btn_2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 200, -1));

        btnOto.setBackground(new java.awt.Color(255, 255, 255));
        btnOto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnOto.setText("Ô tô");
        btnOto.setEnabled(false);
        btnOto.setMaximumSize(new java.awt.Dimension(50, 20));
        btnOto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOtoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOtoMouseEntered(evt);
            }
        });
        btnOto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtoActionPerformed(evt);
            }
        });
        jPanel1.add(btnOto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 109, -1));

        btnCoiXay.setBackground(new java.awt.Color(255, 255, 255));
        btnCoiXay.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCoiXay.setText("Cối Xay");
        btnCoiXay.setEnabled(false);
        btnCoiXay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoiXayActionPerformed(evt);
            }
        });
        jPanel1.add(btnCoiXay, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 40, 85, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("3D");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        btnHinhCau.setBackground(new java.awt.Color(255, 255, 255));
        btnHinhCau.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnHinhCau.setText("Cầu");
        btnHinhCau.setEnabled(false);
        btnHinhCau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHinhCauMouseClicked(evt);
            }
        });
        jPanel1.add(btnHinhCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, -1));

        btnHinhNon.setBackground(new java.awt.Color(255, 255, 255));
        btnHinhNon.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnHinhNon.setText("Nón");
        btnHinhNon.setEnabled(false);
        btnHinhNon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHinhNonMouseClicked(evt);
            }
        });
        btnHinhNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHinhNonActionPerformed(evt);
            }
        });
        jPanel1.add(btnHinhNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        p_inputHinhNon.setBackground(new java.awt.Color(204, 255, 255));
        p_inputHinhNon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel6.setText("Tâm : ");
        p_inputHinhNon.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 39, 25));

        jLabel7.setText("X");
        p_inputHinhNon.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 16, -1, -1));

        jLabel8.setText("Y");
        p_inputHinhNon.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 45, -1, -1));

        jLabel9.setText("Z");
        p_inputHinhNon.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 71, -1, -1));
        p_inputHinhNon.add(tf_xTamNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 13, 63, -1));
        p_inputHinhNon.add(tf_zTamNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 68, 63, -1));
        p_inputHinhNon.add(tf_yTamNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 42, 63, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel10.setText("Bán Kính : ");
        p_inputHinhNon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));
        p_inputHinhNon.add(tf_rNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 94, 63, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        p_inputHinhNon.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 158, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel11.setText("Chiều Cao : ");
        p_inputHinhNon.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));
        p_inputHinhNon.add(tf_hNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 120, 63, -1));

        jPanel1.add(p_inputHinhNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, -1));

        p_inputHinhCau.setBackground(new java.awt.Color(204, 255, 255));
        p_inputHinhCau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tâm : ");
        p_inputHinhCau.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 39, 25));

        jLabel2.setText("X");
        p_inputHinhCau.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 16, -1, -1));

        jLabel3.setText("Y");
        p_inputHinhCau.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 45, -1, -1));

        jLabel4.setText("Z");
        p_inputHinhCau.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 71, -1, -1));
        p_inputHinhCau.add(tf_xCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 13, 63, -1));
        p_inputHinhCau.add(tf_zCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 68, 63, -1));
        p_inputHinhCau.add(tf_yCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 42, 63, -1));

        jLabel5.setText("Bán Kính : ");
        p_inputHinhCau.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));
        p_inputHinhCau.add(tf_rCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 94, 63, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        p_inputHinhCau.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 143, -1, -1));

        jPanel1.add(p_inputHinhCau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tọa Độ Các Điểm");

        jLabel13.setText("Tâm :");

        jLabel14.setText("Đỉnh :");

        jLabel15.setText("A :");

        jLabel16.setText("B : ");

        lb_nonTam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_nonTam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_nonDinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_nonDinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_nonA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_nonA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_nonB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_nonB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p_thongTinNonLayout = new javax.swing.GroupLayout(p_thongTinNon);
        p_thongTinNon.setLayout(p_thongTinNonLayout);
        p_thongTinNonLayout.setHorizontalGroup(
            p_thongTinNonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_thongTinNonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_thongTinNonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(p_thongTinNonLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(17, 17, 17)
                        .addComponent(lb_nonB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_thongTinNonLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_nonTam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_thongTinNonLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(lb_nonDinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_thongTinNonLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(19, 19, 19)
                        .addComponent(lb_nonA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_thongTinNonLayout.setVerticalGroup(
            p_thongTinNonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_thongTinNonLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinNonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lb_nonTam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinNonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lb_nonDinh))
                .addGap(19, 19, 19)
                .addGroup(p_thongTinNonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lb_nonA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinNonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(lb_nonB))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jPanel1.add(p_thongTinNon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, 160));

        btn_HHCN.setBackground(new java.awt.Color(255, 255, 255));
        btn_HHCN.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_HHCN.setText("HHCN");
        btn_HHCN.setEnabled(false);
        btn_HHCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HHCNActionPerformed(evt);
            }
        });
        jPanel1.add(btn_HHCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        p_inputHHCN.setBackground(new java.awt.Color(204, 255, 255));
        p_inputHHCN.setPreferredSize(new java.awt.Dimension(120, 250));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel20.setText("Tâm  ");

        jLabel21.setText("X : ");

        jLabel22.setText("Y : ");

        jLabel23.setText("Z :");

        tf_HCNY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_HCNYActionPerformed(evt);
            }
        });

        jLabel24.setText("Rộng :");

        jLabel25.setText("Dài :");

        jLabel26.setText("Cao :");

        tf_HCNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_HCNCActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_inputHHCNLayout = new javax.swing.GroupLayout(p_inputHHCN);
        p_inputHHCN.setLayout(p_inputHHCNLayout);
        p_inputHHCNLayout.setHorizontalGroup(
            p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_inputHHCNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_inputHHCNLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p_inputHHCNLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_HCNX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_inputHHCNLayout.createSequentialGroup()
                                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_HCNY)
                                    .addComponent(tf_HCNZ)
                                    .addComponent(tf_HCNR)
                                    .addComponent(tf_HCND)
                                    .addComponent(tf_HCNC)))))
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_inputHHCNLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        p_inputHHCNLayout.setVerticalGroup(
            p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_inputHHCNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(tf_HCNX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_HCNY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_HCNZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_HCNR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_HCND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_inputHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_HCNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1.add(p_inputHHCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 260));

        p_heToaDo.setPreferredSize(new java.awt.Dimension(800, 650));

        javax.swing.GroupLayout p_heToaDoLayout = new javax.swing.GroupLayout(p_heToaDo);
        p_heToaDo.setLayout(p_heToaDoLayout);
        p_heToaDoLayout.setHorizontalGroup(
            p_heToaDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        p_heToaDoLayout.setVerticalGroup(
            p_heToaDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        p_thongTinToaDo.setBackground(new java.awt.Color(102, 102, 102));
        p_thongTinToaDo.setPreferredSize(new java.awt.Dimension(180, 700));
        p_thongTinToaDo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Thông tin tọa độ");
        p_thongTinToaDo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 160, -1));

        p_thongTinOto.setPreferredSize(new java.awt.Dimension(160, 700));

        lb_oto1.setText("A1(100,100)");

        lb_oto2.setText("A1(100,100)");

        lb_oto4.setText("A1(100,100)");

        lb_oto3.setText("A1(100,100)");

        lb_oto6.setText("A1(100,100)");

        lb_oto5.setText("A1(100,100)");

        lb_oto8.setText("A1(100,100)");

        lb_oto7.setText("A1(100,100)");

        lb_oto10.setText("A1(100,100)");

        lb_oto9.setText("A1(100,100)");

        lb_oto12.setText("A1(100,100)");

        lb_oto11.setText("A1(100,100)");

        lb_oto14.setText("A1(100,100)");

        lb_oto13.setText("A1(100,100)");

        lb_oto16.setText("A1(100,100)");

        lb_oto15.setText("A1(100,100)");

        lb_oto18.setText("A1(100,100)");

        lb_oto17.setText("A1(100,100)");

        lb_oto20.setText("A1(100,100)");

        lb_oto19.setText("A1(100,100)");

        lb_oto22.setText("A1(100,100)");

        lb_oto21.setText("A1(100,100)");

        lb_oto24.setText("A1(100,100)");

        lb_oto23.setText("A1(100,100)");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Ô tô đỏ");

        lb_2oto24.setText("A1(100,100)");

        lb_2oto23.setText("A1(100,100)");

        lb_2oto18.setText("A1(100,100)");

        lb_2oto17.setText("A1(100,100)");

        lb_2oto20.setText("A1(100,100)");

        lb_2oto19.setText("A1(100,100)");

        lb_2oto22.setText("A1(100,100)");

        lb_2oto21.setText("A1(100,100)");

        lb_2oto1.setText("A1(100,100)");

        lb_2oto2.setText("A1(100,100)");

        lb_2oto4.setText("A1(100,100)");

        lb_2oto3.setText("A1(100,100)");

        lb_2oto6.setText("A1(100,100)");

        lb_2oto5.setText("A1(100,100)");

        lb_2oto8.setText("A1(100,100)");

        lb_2oto7.setText("A1(100,100)");

        lb_2oto10.setText("A1(100,100)");

        lb_2oto9.setText("A1(100,100)");

        lb_2oto12.setText("A1(100,100)");

        lb_2oto11.setText("A1(100,100)");

        lb_2oto14.setText("A1(100,100)");

        lb_2oto13.setText("A1(100,100)");

        lb_2oto16.setText("A1(100,100)");

        lb_2oto15.setText("A1(100,100)");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Bánh Xe");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Bánh Xe");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Ô tô đen");

        javax.swing.GroupLayout p_thongTinOtoLayout = new javax.swing.GroupLayout(p_thongTinOto);
        p_thongTinOto.setLayout(p_thongTinOtoLayout);
        p_thongTinOtoLayout.setHorizontalGroup(
            p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                        .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto2))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto4))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto6))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto8))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto10))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto12))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto14))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto16))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_oto18))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto20))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto22))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_oto23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_oto24))
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto2))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto4))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto6))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto8))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto10))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto12))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto14))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto16))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_2oto18))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto20))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto22))
                            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                                .addComponent(lb_2oto23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_2oto24)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_thongTinOtoLayout.setVerticalGroup(
            p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_thongTinOtoLayout.createSequentialGroup()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto1)
                    .addComponent(lb_oto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto3)
                    .addComponent(lb_oto4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto5)
                    .addComponent(lb_oto6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto7)
                    .addComponent(lb_oto8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto9)
                    .addComponent(lb_oto10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto11)
                    .addComponent(lb_oto12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto13)
                    .addComponent(lb_oto14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto15)
                    .addComponent(lb_oto16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto17)
                    .addComponent(lb_oto18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto19)
                    .addComponent(lb_oto20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto21)
                    .addComponent(lb_oto22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_oto23)
                    .addComponent(lb_oto24))
                .addGap(9, 9, 9)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto1)
                    .addComponent(lb_2oto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto3)
                    .addComponent(lb_2oto4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto5)
                    .addComponent(lb_2oto6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto7)
                    .addComponent(lb_2oto8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto9)
                    .addComponent(lb_2oto10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto11)
                    .addComponent(lb_2oto12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto13)
                    .addComponent(lb_2oto14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto15)
                    .addComponent(lb_2oto16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto17)
                    .addComponent(lb_2oto18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto19)
                    .addComponent(lb_2oto20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto21)
                    .addComponent(lb_2oto22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinOtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_2oto23)
                    .addComponent(lb_2oto24))
                .addContainerGap())
        );

        p_thongTinToaDo.add(p_thongTinOto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 610));

        p_thongTinHHCN.setBackground(new java.awt.Color(255, 255, 255));

        lb_HHCN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN4.setText("jLabel27");

        lb_HHCN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN3.setText("jLabel27");

        lb_HHCN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN1.setText("jLabel27");

        lb_HHCN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN2.setText("jLabel27");

        lb_HHCN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN5.setText("jLabel27");

        lb_HHCN6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN6.setText("jLabel27");

        lb_HHCN7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN7.setText("jLabel27");

        lb_HHCN8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HHCN8.setText("jLabel27");

        javax.swing.GroupLayout p_thongTinHHCNLayout = new javax.swing.GroupLayout(p_thongTinHHCN);
        p_thongTinHHCN.setLayout(p_thongTinHHCNLayout);
        p_thongTinHHCNLayout.setHorizontalGroup(
            p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_thongTinHHCNLayout.createSequentialGroup()
                .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_HHCN1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_HHCN3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_HHCN5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_HHCN7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p_thongTinHHCNLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(lb_HHCN2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lb_HHCN4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_thongTinHHCNLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_HHCN6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_HHCN8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        p_thongTinHHCNLayout.setVerticalGroup(
            p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_thongTinHHCNLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_HHCN2)
                    .addComponent(lb_HHCN1))
                .addGap(6, 6, 6)
                .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_HHCN4)
                    .addComponent(lb_HHCN3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_HHCN5)
                    .addComponent(lb_HHCN6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_thongTinHHCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_HHCN7)
                    .addComponent(lb_HHCN8))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        p_thongTinToaDo.add(p_thongTinHHCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_heToaDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_thongTinToaDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addComponent(p_heToaDo, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_thongTinToaDo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String inToaDo(Point p, int i) {
        String tmp = "X" + i + "(" + (int) p.getX() + "," + (int) p.getY() + ")";
        return tmp;
    }

    public String inToaDo3D(Point3D p) {
        String tmp = "(" + (int) p.getX() + "," + (int) p.getY() + "," + (int) p.getZ() + ")";
        return tmp;
    }

    public String inToaDo3DS(Point3D p, String s) {
        String tmp = s + "(" + (int) p.getX() + "," + (int) p.getY() + "," + (int) p.getZ() + ")";
        return tmp;
    }

    public void getListToaDoNon(HinhNon non) {
        lb_nonTam.setText(inToaDo3D(non.getTam()));
        lb_nonDinh.setText(inToaDo3D(non.getDinh()));
        lb_nonA.setText(inToaDo3D(non.getA1()));
        lb_nonB.setText(inToaDo3D(non.getB1()));
    }

    public void getListToaDoHHCN(HinhHopChuNhat h) {
        lb_HHCN1.setText(inToaDo3DS(h.getA(), "A"));
        lb_HHCN2.setText(inToaDo3DS(h.getB(), "B"));
        lb_HHCN3.setText(inToaDo3DS(h.getC(), "C"));
        lb_HHCN4.setText(inToaDo3DS(h.getD(), "D"));
        lb_HHCN5.setText(inToaDo3DS(h.getA1(), "E"));
        lb_HHCN6.setText(inToaDo3DS(h.getB1(), "F"));
        lb_HHCN7.setText(inToaDo3DS(h.getC1(), "G"));
        lb_HHCN8.setText(inToaDo3DS(h.getD1(), "H"));
    }

    public void getListToaDoOto(Oto car) {
        ArrayList<Point> list = car.getListPoint();
        lb_oto1.setText(inToaDo(list.get(0), 0));
        lb_oto2.setText(inToaDo(list.get(1), 1));
        lb_oto3.setText(inToaDo(list.get(2), 2));
        lb_oto4.setText(inToaDo(list.get(3), 3));
        lb_oto5.setText(inToaDo(list.get(4), 4));
        lb_oto6.setText(inToaDo(list.get(5), 5));
        lb_oto7.setText(inToaDo(list.get(6), 6));
        lb_oto8.setText(inToaDo(list.get(7), 7));
        lb_oto9.setText(inToaDo(list.get(8), 8));
        lb_oto10.setText(inToaDo(list.get(9), 9));
        lb_oto11.setText(inToaDo(list.get(10), 10));
        lb_oto12.setText(inToaDo(list.get(11), 11));
        lb_oto13.setText(inToaDo(list.get(12), 12));
        lb_oto14.setText(inToaDo(list.get(13), 13));
        lb_oto15.setText(inToaDo(list.get(14), 14));
        lb_oto16.setText(inToaDo(list.get(15), 15));
        lb_oto17.setText(inToaDo(list.get(16), 16));
        lb_oto18.setText(inToaDo(list.get(17), 17));
        lb_oto19.setText(inToaDo(list.get(18), 18));
        lb_oto20.setText(inToaDo(list.get(19), 19));
        lb_oto21.setText(inToaDo(list.get(20), 20));
        lb_oto22.setText(inToaDo(list.get(21), 21));
        lb_oto23.setText(inToaDo(list.get(22), 22));
        lb_oto24.setText(inToaDo(list.get(23), 23));
    }

    public void getListToaDoOto2(Oto car) {
        ArrayList<Point> list = car.getListPoint();
        lb_2oto1.setText(inToaDo(list.get(0), 0));
        lb_2oto2.setText(inToaDo(list.get(1), 1));
        lb_2oto3.setText(inToaDo(list.get(2), 2));
        lb_2oto4.setText(inToaDo(list.get(3), 3));
        lb_2oto5.setText(inToaDo(list.get(4), 4));
        lb_2oto6.setText(inToaDo(list.get(5), 5));
        lb_2oto7.setText(inToaDo(list.get(6), 6));
        lb_2oto8.setText(inToaDo(list.get(7), 7));
        lb_2oto9.setText(inToaDo(list.get(8), 8));
        lb_2oto10.setText(inToaDo(list.get(9), 9));
        lb_2oto11.setText(inToaDo(list.get(10), 10));
        lb_2oto12.setText(inToaDo(list.get(11), 11));
        lb_2oto13.setText(inToaDo(list.get(12), 12));
        lb_2oto14.setText(inToaDo(list.get(13), 13));
        lb_2oto15.setText(inToaDo(list.get(14), 14));
        lb_2oto16.setText(inToaDo(list.get(15), 15));
        lb_2oto17.setText(inToaDo(list.get(16), 16));
        lb_2oto18.setText(inToaDo(list.get(17), 17));
        lb_2oto19.setText(inToaDo(list.get(18), 18));
        lb_2oto20.setText(inToaDo(list.get(19), 19));
        lb_2oto21.setText(inToaDo(list.get(20), 20));
        lb_2oto22.setText(inToaDo(list.get(21), 21));
        lb_2oto23.setText(inToaDo(list.get(22), 22));
        lb_2oto24.setText(inToaDo(list.get(23), 23));
    }
    private void btnCoiXayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoiXayActionPerformed
        // TODO add your handling code here:
        p_thongTinOto.setVisible(false);
        CoiXay coi = new CoiXay();
        CoiXay coi2 = new CoiXay();
        Graphics g = p_heToaDo.getGraphics();
        coi.veTru(g);
        coi.veCanh(g);
        coi2.doiXung("Oy");
        int i = 0;
        while (i < 20) {
            i++;
            g.clearRect(1, 1, 800, 650);
            CoBan.drawCoordinateSys(g);
            coi.veTru(g);
            coi.quayCanh();
            coi.veCanh(g);
            coi2.veTru(g);
            coi2.quayCanh();
            coi2.veCanh(g);
            try {
                sleep(50);
            } catch (InterruptedException ex) {
                Logger.getLogger(Main_F.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        g.clearRect(1, 1, 800, 650);
        CoBan.drawCoordinateSys(g);
        coi = new CoiXay();
        coi.veTru(g);
        coi.veCanh(g);
        coi2 = new CoiXay();
        coi2.doiXung("Oy");
        coi2.veTru(g);
        coi2.veCanh(g);
    }//GEN-LAST:event_btnCoiXayActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        btnOto.setEnabled(false);
        btnCoiXay.setEnabled(false);
        btnHinhCau.setEnabled(true);
        btnHinhNon.setEnabled(true);
        btn_HHCN.setEnabled(true);
        p_thongTinOto.setVisible(false);
        if (p_inputHinhNon.isVisible() || p_inputHinhCau.isVisible() || p_inputHHCN.isVisible()) {
            p_inputHinhNon.setVisible(false);
            p_inputHinhCau.setVisible(false);
            p_thongTinNon.setVisible(false);
            p_inputHHCN.setVisible(false);
        }

        //p_heToaDo.setVisible(true);
        Graphics g = p_heToaDo.getGraphics();
        g.clearRect(1, 1, 800, 700);
        CoBan.drawCoordinateSys3D(g);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2DActionPerformed

        // TODO add your handling code here:
        p_inputHinhNon.setVisible(false);
        p_inputHinhCau.setVisible(false);
        p_inputHHCN.setVisible(false);
        btnHinhCau.setEnabled(false);
        btnHinhNon.setEnabled(false);
        btn_HHCN.setEnabled(false);
        btnOto.setEnabled(true);
        btnCoiXay.setEnabled(true);
        //p_thongTinOto.setVisible(true);
        // p_heToaDo.setVisible(true);
        Graphics g = p_heToaDo.getGraphics();
        g.clearRect(1, 1, 800, 700);
        CoBan.drawCoordinateSys(g);
        //p_heToaDo.setVisible(true);
        if (p_thongTinOto.isVisible()) {
            p_thongTinOto.setVisible(false);
        }
        p_thongTinNon.setVisible(false);
        p_thongTinHHCN.setVisible(false);
    }//GEN-LAST:event_btn_2DActionPerformed

    private void btnOtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_btnOtoMouseClicked

    private void btnOtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtoActionPerformed
        // TODO add your handling code here:
        Oto car = new Oto();
        Oto car2 = new Oto();
        Oto car3 = new Oto();
        car3.thuPhong(1.5);
        car3.tinhTienXe(-80, 20);
        car2.doiXung("Ox");
        // car2.thuPhong(0.5);
        Graphics g = p_heToaDo.getGraphics();
        p_thongTinOto.setVisible(true);
        getListToaDoOto(car);
        getListToaDoOto2(car2);
        car.ve(g, Color.BLACK);
        car2.ve(g, Color.RED);
        int i = 0;
        int j = 0;
        while (j < 1) {
            g.clearRect(1, 1, 800, 650);
            if (i > -30) {
                CoBan.drawCoordinateSys(g);
                i = i - 2;
                car2.tinhTienXe(i, 0);
                car2.quayBanh();
                car2.ve(g, Color.RED);
                car.tinhTienXe(i, 0);
                car.quayBanh();
                car.ve(g, Color.BLACK);
                try {
                    sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Main_F.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                i = 0;
                car = new Oto();
                car2 = new Oto();
                j++;
            }
        }
        CoBan.drawCoordinateSys(g);
        //car.quayXe(60);
        car.ve(g, Color.BLACK);
        car2.doiXung("Ox");
        //car2.thuPhong(0.5);

        car2.ve(g, Color.red);
        getListToaDoOto(car);
        getListToaDoOto2(car2);
        car3.ve(g, Color.BLUE);
       

    }//GEN-LAST:event_btnOtoActionPerformed

    private void btnHinhCauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHinhCauMouseClicked
        // TODO add your handling code here:
        p_inputHinhNon.setVisible(false);
        p_inputHinhCau.setVisible(true);
        p_thongTinNon.setVisible(false);
        p_inputHHCN.setVisible(false);
        p_thongTinHHCN.setVisible(false);
    }//GEN-LAST:event_btnHinhCauMouseClicked

    private void btnHinhNonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHinhNonMouseClicked
        // TODO add your handling code here:
        p_inputHinhCau.setVisible(false);
        p_inputHinhNon.setVisible(true);
        p_inputHHCN.setVisible(false);
        p_thongTinHHCN.setVisible(false);
    }//GEN-LAST:event_btnHinhNonMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String X, Y, Z, R, H;
        boolean isOk = true;
        X = tf_xTamNon.getText();
        Y = tf_yTamNon.getText();
        Z = tf_zTamNon.getText();
        R = tf_rNon.getText();
        H = tf_hNon.getText();
        if (X.isEmpty() || Y.isEmpty() || Z.isEmpty() || R.isEmpty() || H.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn hãy nhập đầy đủ thông số để vẽ hình");
            isOk = false;
        }
        if (!X.matches(CoorRegex) || !Y.matches(CoorRegex) || !Z.matches(CoorRegex)) {
            JOptionPane.showMessageDialog(rootPane, "Tọa độ tâm là chữ số và dấu \"-\"");
            isOk = false;
        }
        if (!R.matches(lengthRegex) || !H.matches(lengthRegex)) {
            JOptionPane.showMessageDialog(rootPane, "Độ dài là các chữ số");
            isOk = false;
        }
        if (isOk == true) {
            int x = Integer.parseInt(X);
            int y = Integer.parseInt(Y);
            int z = Integer.parseInt(Z);
            int r = Integer.parseInt(R);
            int h = Integer.parseInt(H);
            if (r < 1 || h < 1) {
                JOptionPane.showMessageDialog(rootPane, "Độ dài không thể nhỏ hơn 1");
            } else {
                HinhNon non = new HinhNon(x, y, z, r, h);
                Graphics g = p_heToaDo.getGraphics();
                g.clearRect(1, 1, 800, 650);
                CoBan.drawCoordinateSys3D(g);
                non.ve(g);
                p_thongTinNon.setVisible(true);
                getListToaDoNon(non);
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String X, Y, Z, R;
        X = tf_xCau.getText();
        Y = tf_yCau.getText();
        Z = tf_zCau.getText();
        R = tf_rCau.getText();
        boolean isOk = true;
        if (X.isEmpty() || Y.isEmpty() || Z.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn hãy nhập đầy đủ thông số để vẽ hình");
        }
        if (!X.matches(CoorRegex) || !Y.matches(CoorRegex) || !Z.matches(CoorRegex)) {
            JOptionPane.showMessageDialog(rootPane, "Tọa độ tâm là chữ số và dấu \"-\"");
            isOk = false;
        }
        if (!R.matches(lengthRegex)) {
            JOptionPane.showMessageDialog(rootPane, "Độ dài là các chữ số");
            isOk = false;
        }
        if (isOk == true) {
            int x = Integer.parseInt(X);
            int y = Integer.parseInt(Y);
            int z = Integer.parseInt(Z);
            int r = Integer.parseInt(R);
            if (r < 1) {
                JOptionPane.showMessageDialog(rootPane, "Độ dài không thể nhỏ hơn 1");
            } else {
                HinhCau cau = new HinhCau(x, y, z, r);
                Graphics g = p_heToaDo.getGraphics();
                g.clearRect(1, 1, 800, 650);
                CoBan.drawCoordinateSys3D(g);
                cau.ve(g);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnOtoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtoMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOtoMouseEntered

    private void tf_HCNYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_HCNYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_HCNYActionPerformed

    private void tf_HCNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_HCNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_HCNCActionPerformed

    private void btn_HHCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HHCNActionPerformed
        // TODO add your handling code here:
        p_inputHHCN.setVisible(true);
        p_inputHinhCau.setVisible(false);
        p_inputHinhNon.setVisible(false);
        p_thongTinNon.setVisible(false);
    }//GEN-LAST:event_btn_HHCNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String X, Y, Z, R, D, C;
        boolean isOk = true;
        X = tf_HCNX.getText();
        Y = tf_HCNY.getText();
        Z = tf_HCNZ.getText();
        R = tf_HCNR.getText();
        D = tf_HCND.getText();
        C = tf_HCNC.getText();
        if (X.isEmpty() || Y.isEmpty() || Z.isEmpty() || R.isEmpty() || D.isEmpty() || C.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn hãy nhập đầy đủ thông số để vẽ hình");
            isOk = false;
        }
        if (!X.matches(CoorRegex) || !Y.matches(CoorRegex) || !Z.matches(CoorRegex)) {
            JOptionPane.showMessageDialog(rootPane, "Tọa độ tâm là chữ số và dấu \"-\"");
            isOk = false;
        }
        if (!R.matches(lengthRegex) || !D.matches(lengthRegex) || !C.matches(lengthRegex)) {
            JOptionPane.showMessageDialog(rootPane, "Độ dài là các chữ số");
            isOk = false;
        }
        if (isOk) {
            int x = Integer.parseInt(X);
            int y = Integer.parseInt(Y);
            int z = Integer.parseInt(Z);
            int r = Integer.parseInt(R);
            int d = Integer.parseInt(D);
            int c = Integer.parseInt(C);
            HinhHopChuNhat h = new HinhHopChuNhat(x, y, z, r, d, c);
            Graphics g = p_heToaDo.getGraphics();
            g.clearRect(1, 1, 800, 650);
            CoBan.drawCoordinateSys3D(g);
            h.ve(g);
            p_thongTinHHCN.setVisible(true);
            getListToaDoHHCN(h);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHinhNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHinhNonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHinhNonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_F().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoiXay;
    private javax.swing.JButton btnHinhCau;
    private javax.swing.JButton btnHinhNon;
    private javax.swing.JButton btnOto;
    private javax.swing.JButton btn_2D;
    private javax.swing.JButton btn_HHCN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_2oto1;
    private javax.swing.JLabel lb_2oto10;
    private javax.swing.JLabel lb_2oto11;
    private javax.swing.JLabel lb_2oto12;
    private javax.swing.JLabel lb_2oto13;
    private javax.swing.JLabel lb_2oto14;
    private javax.swing.JLabel lb_2oto15;
    private javax.swing.JLabel lb_2oto16;
    private javax.swing.JLabel lb_2oto17;
    private javax.swing.JLabel lb_2oto18;
    private javax.swing.JLabel lb_2oto19;
    private javax.swing.JLabel lb_2oto2;
    private javax.swing.JLabel lb_2oto20;
    private javax.swing.JLabel lb_2oto21;
    private javax.swing.JLabel lb_2oto22;
    private javax.swing.JLabel lb_2oto23;
    private javax.swing.JLabel lb_2oto24;
    private javax.swing.JLabel lb_2oto3;
    private javax.swing.JLabel lb_2oto4;
    private javax.swing.JLabel lb_2oto5;
    private javax.swing.JLabel lb_2oto6;
    private javax.swing.JLabel lb_2oto7;
    private javax.swing.JLabel lb_2oto8;
    private javax.swing.JLabel lb_2oto9;
    private javax.swing.JLabel lb_HHCN1;
    private javax.swing.JLabel lb_HHCN2;
    private javax.swing.JLabel lb_HHCN3;
    private javax.swing.JLabel lb_HHCN4;
    private javax.swing.JLabel lb_HHCN5;
    private javax.swing.JLabel lb_HHCN6;
    private javax.swing.JLabel lb_HHCN7;
    private javax.swing.JLabel lb_HHCN8;
    private javax.swing.JLabel lb_nonA;
    private javax.swing.JLabel lb_nonB;
    private javax.swing.JLabel lb_nonDinh;
    private javax.swing.JLabel lb_nonTam;
    private javax.swing.JLabel lb_oto1;
    private javax.swing.JLabel lb_oto10;
    private javax.swing.JLabel lb_oto11;
    private javax.swing.JLabel lb_oto12;
    private javax.swing.JLabel lb_oto13;
    private javax.swing.JLabel lb_oto14;
    private javax.swing.JLabel lb_oto15;
    private javax.swing.JLabel lb_oto16;
    private javax.swing.JLabel lb_oto17;
    private javax.swing.JLabel lb_oto18;
    private javax.swing.JLabel lb_oto19;
    private javax.swing.JLabel lb_oto2;
    private javax.swing.JLabel lb_oto20;
    private javax.swing.JLabel lb_oto21;
    private javax.swing.JLabel lb_oto22;
    private javax.swing.JLabel lb_oto23;
    private javax.swing.JLabel lb_oto24;
    private javax.swing.JLabel lb_oto3;
    private javax.swing.JLabel lb_oto4;
    private javax.swing.JLabel lb_oto5;
    private javax.swing.JLabel lb_oto6;
    private javax.swing.JLabel lb_oto7;
    private javax.swing.JLabel lb_oto8;
    private javax.swing.JLabel lb_oto9;
    private javax.swing.JPanel p_heToaDo;
    private javax.swing.JPanel p_inputHHCN;
    private javax.swing.JPanel p_inputHinhCau;
    private javax.swing.JPanel p_inputHinhNon;
    private javax.swing.JPanel p_thongTinHHCN;
    private javax.swing.JPanel p_thongTinNon;
    private javax.swing.JPanel p_thongTinOto;
    private javax.swing.JPanel p_thongTinToaDo;
    private javax.swing.JTextField tf_HCNC;
    private javax.swing.JTextField tf_HCND;
    private javax.swing.JTextField tf_HCNR;
    private javax.swing.JTextField tf_HCNX;
    private javax.swing.JTextField tf_HCNY;
    private javax.swing.JTextField tf_HCNZ;
    private javax.swing.JTextField tf_hNon;
    private javax.swing.JTextField tf_rCau;
    private javax.swing.JTextField tf_rNon;
    private javax.swing.JTextField tf_xCau;
    private javax.swing.JTextField tf_xTamNon;
    private javax.swing.JTextField tf_yCau;
    private javax.swing.JTextField tf_yTamNon;
    private javax.swing.JTextField tf_zCau;
    private javax.swing.JTextField tf_zTamNon;
    // End of variables declaration//GEN-END:variables
}
